[package]
name = "bios-enhance-wasm"
version = "0.1.6"
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[lib]
name = "bios_enhance_wasm"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
lazy_static.workspace = true

# crypto
base64 = { version = "0.22" }
hex = { version = "0.4" }
libsm = { version = "=0.6.0" }
num-bigint = { version = "0.4.3" }

# wasm
console_error_panic_hook = { version = "0" }
wee_alloc = { version = "0" }
wasm-bindgen = { version = "0" }
wasm-bindgen-futures = { version = "0" }
serde-wasm-bindgen = { version = "0" }
js-sys = { version = "0" }
web-sys = { version = "0", features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestCredentials',
  'RequestMode',
  'Response',
  'Window',
  'console',
  'BroadcastChannel',
  'Storage',
] }
wasm-bindgen-test = { version = "0" }

# see: https://github.com/rust-random/getrandom/issues/231
# see: https://github.com/rustwasm/wasm-bindgen/pull/3031
getrandom = { version = "^0.2", features = ["js"] }

# TODO
rand = { version = "0.8" }
rand_core = { version = "0.6" }

#[cfg(not(target_arch = "wasm32"))]
serde_json = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { version = "0" }
