[cs]
[csm.spi-conf]


[fw]
[fw.app]
id = "spi-conf-serv"
name = "SPI Conf Services"
desc = "SPI Conf Services"
version = "0.1.0"
default_lang = "zh-cn"

[fw.web_server]
port = 8080
[fw.web_server.modules.spi-conf]
title = "SPi conf Component"
doc_urls = [["test env", "http://localhost:8080/"]]

[fw.db]
url = "mysql://root:ENC(5892ae51dbeedacdf10ba4c0d7af42a7)@localhost:3306/test"

[fw.cache]
url = "redis://:ENC(5892ae51dbeedacdf10ba4c0d7af42a7)@127.0.0.1:6379"

[fw.mq]
url = "amqp://user:ENC(5892ae51dbeedacdf10ba4c0d7af42a7)@127.0.0.1:5672/%2f"

[fw.adv]
salt = "qa2df6gr452lfr3e"